# Utiliza la imagen oficial de Postgres como imagen base.
# Esta imagen contiene todo lo necesario para ejecutar una base de datos Postgres.
FROM postgres

# Expone el puerto 5432.
# Esto informa a Docker que el contenedor escucha en este puerto,
# permitiendo la comunicación con otros contenedores en la misma red.
EXPOSE 5432
